Fix unused-features linter
```
   error: failed to compile `cargo-unused-features: v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-install3SVrCi`.
  To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

  Caused by:
    rustc 1.78.0 is not supported by the following package:
      cargo-util@0.2.14 requires rustc 1.79
    Try re-running `cargo install` with `--locked`
```

Signed-off-by: Lukas Pukenis <lukas.pukenis@nordsec.com>